def coinchange():
    ui = float(input("Enter the amt of coins? ").strip())
    q = int(ui / .25)
    tmp = round(ui % .25, 5)
    #print("1:>>", tmp)
    d = int(tmp / .10)
    tmp = round(tmp % .10, 5)
    #print("2:>>", tmp)
    n = int(tmp / .05)
    tmp = tmp - (n*.05)
    #print("3:>>", tmp)
    p = int(float(round(tmp, 4)) / .01)
    print("Q: ",q)
    print("D: ",d)
    print("N: ",n)
    print("P: ",p)
